import { ParamSet } from "../types";

export const defaultParams: ParamSet = [
  {
    id: "mkp1",
    name: "iterationsNum",
    type: "SLIDER",
    value: 8,
    range: [1, 10],
    step: 1,
    label: "P1",
    group: 1,
  },
  {
    id: "mkp5",
    name: "scaleCtrl",
    type: "SLIDER",
    value: 1,
    range: [1, 3],
    step: 0.01,
    label: "P3",
    group: 0,
  },
  {
    id: "mkp2",
    name: "angleRotationStepCtrl",
    type: "SLIDER",
    value: 30,
    range: [0, 60],
    step: 0.1,
    label: "P2",
    group: 0,
  },
  {
    id: "mkp3",
    name: "lengthCtrl",
    type: "SLIDER",
    value: 1,
    range: [0.25, 5],
    step: 0.01,
    label: "P4",
    group: 0,
  },
  {
    id: "mkp4",
    name: "empty",
    type: "SLIDER",
    value: 15,
    range: [0, 30],
    step: 0.1,
    label: "P5",
    group: 0,
  },
  {
    id: "mkp6",
    name: "empty",
    type: "SLIDER",
    value: 1,
    range: [0, 2],
    step: 0.01,
    label: "P6",
    group: 0,
  },
  {
    id: "mkp7",
    name: "empty",
    type: "SLIDER",
    value: 1,
    range: [0, 2],
    step: 0.01,
    label: "P7",
    group: 0,
  },
];
